resolver: lts-20.18

packages:
  - '.'

apply-ghc-options:
  everything

ghc-options:
  "$everything":
     -fplugin-trustworthy
     -fplugin-library=../result/lib/libwpc-plugin.dylib;wpc-plugin-unit;WPC.Plugin;[]

#     -fplugin-libary=-lwpc-plugin -fplugin=WPC.Plugin -optl-Wl,-rpath,-lwpc-plugin
